# Generated by Django 4.0.4 on 2022-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_regNo', models.IntegerField(unique=True)),
                ('employee_name', models.TextField(unique=True)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_mobile', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
